name: 'ga4_connectors'
version: '1.0.0'

profile: 'ga4'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4_connectors:
    # Config indicated by + and applies to all files under models/microsoft/
    google:
      +materialized: table

# Define variables here
vars:
  ga4_channel_performance_v_1_identifier: ga_4_channel_performance_v_1
  ga4_channel_performance_v_2_identifier: ga_4_channel_performance_v_2
